version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 99
    pull-request-branch-name:
      separator: "-"
