---
name: "Get LambdaLabs Instance Types"
description: "Retrieves the instance types offered by Lambda GPU Cloud and optionally filters based on availability."
inputs:
  available_only:
    description: "Filter out instance types with no available regions"
    required: false
    default: "true"
  names_only:
    description: "Return only the names of the instance types"
    required: false
    default: "false"
  lambda_token:
    description: "The LambdaLabs API token"
    required: true
outputs:
  instance_types:
    description: "The filtered list of instance types or instance type names"
    value: ${{ steps.get-instance-types.outputs.instance_types }}
runs:
  using: "composite"
  steps:
    - name: Copy requirements
      run: cp ${{ github.action_path }}/requirements.txt .tmp-ifera-lambdalabs-get-instance-types-action-requirements.txt
      shell: bash

    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: .tmp-ifera-lambdalabs-get-instance-types-action-requirements.txt

    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash

    - name: Get Instance Types
      id: get-instance-types
      run: python ${{ github.action_path }}/get_instance_types.py
      shell: bash
      env:
        AVAILABLE_ONLY: ${{ inputs.available_only }}
        NAMES_ONLY: ${{ inputs.names_only }}
        LAMBDA_TOKEN: ${{ inputs.lambda_token }}

    - name: Clean up
      run: rm -f .tmp-ifera-lambdalabs-get-instance-types-action-requirements.txt
      shell: bash
